<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseRidGraph>true</UseRidGraph>
        <PublishReadyToRun>true</PublishReadyToRun>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.13" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.13" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.13" />
        <PackageReference Include="Avalonia.Controls.DataGrid" Version="11.3.13" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../MilkiBotFramework/MilkiBotFramework.csproj" />
        <ProjectReference Include="../../Platforms/MilkiBotFramework.Platforms.Mock/MilkiBotFramework.Platforms.Mock.csproj" />
    </ItemGroup>
</Project>
